import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { Auth, useAuth } from "@arcana/auth-react";

export default function Home() {
  const auth = useAuth();
  const provider = auth.provider;
  console.log(provider, "provider");
  const onLogin = async () => {
    const provider = auth.provider;
    try {
      await auth.connect();
      console.log(provider, "provider");
      const chainId = 1;
      console.log(chainId, "chainId");
      await provider.request({
        method: "wallet_switchEthereumChain",
        params: [{ chainId: "0x5001" }],
      });
    } catch (e) {
      if (e.code === 4902) {
        await provider.request({
          method: "wallet_addEthereumChain",
          params: [
            {
              chainId: "0x5001",
              chainName: "Mantle Testnet",
              rpcUrls: ["https://rpc.testnet.mantle.xyz	"],
              nativeCurrency: {
                name: "Mantle",
                symbol: "BIT",
                decimals: 18,
              },
              blockExplorerUrls: ["https://explorer.testnet.mantle.xyz/"],
            },
          ],
        });
      }
      console.log(e, "onLogin");
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button className="p-2 bg-red-300 rounded-xl m-2" onClick={onLogin}>
          Arcana login
        </button>
      </main>
    </>
  );
}
